### PR TITLE
Remove empty sections previously containing embedded videos

### PR DESCRIPTION
**Pull request by kaizoku**
This PR updates the video converter to additionally remove the parent of the embedded video `<iframe>` if there are no other children. This was in certain cases creating a large empty area on the page above the description and video.

**JIRA Tickets**: TNL-8000

**Testing instructions**:

1. Convert course using `--link-file` flag to utilize video conversion
2. Verify that converted videos no longer have large empty sections above the video description

**Author notes and concerns**:

1. This was a side effect of the empty `<p>` element which previously contained the `<iframe>` having a style attribute with styles creating an empty area. Might there be any cases where it would be desirable to retain this styling even once the iframe is removed?

**Reviewers**
- [ ] @alangsto

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @kaizoku! I've created [OSPR-5674](https://openedx.atlassian.net/browse/OSPR-5674) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by alangsto — CHANGES_REQUESTED** [review]
This LGTM, but could you make sure that the code coverage checks pass? Thanks!

**Comment by kaizoku** [comment]
@alangsto sure, I got onto codecov and found the issue was a partial coverage over an if statement.
I added another section to the test IMSCC course to cover both positive and negative matches for that if statement.

**Review by alangsto — APPROVED** [review]

**Comment by edx-webhook** [comment]
@kaizoku 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/cc2olx&entry.867055334=https://github.com/edx/cc2olx/pull/52&entry.1484655318=https://github.com/kaizoku&entry.752974735=2021-03-16+13:32&entry.1917517419=2021-03-17+14:04&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by natabene** [comment]
@kaizoku Thank you for your contribution. @alangsto Thank you for your quick review and merge!

**Pull request merged**
