### PR TITLE
Add 'formatting' tox environment

### PR DESCRIPTION
**Pull request by 0x29a**
I mentioned that in fact Travis doesn't check formatting. This PR should fix it.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @0x29a! I've created [OSPR-5296](https://openedx.atlassian.net/browse/OSPR-5296) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@0x29a Thank you for your contribution. Is this ready for our review?

**Review by alangsto — APPROVED** [review]

**Comment by natabene** [comment]
@alangsto Please merge when you can.

**Comment by alangsto** [comment]
@natabene planning on merging once the checks are successful.

**Comment by 0x29a** [comment]
@natabene, this isn't ready for merge, sorry for the delay in answer.

@alangsto, I encountered some troubles with `black` when using Python `3.5` and currently trying to resolve them. I'll keep you updated in Slack channel.

**Comment by natabene** [comment]
@0x29a Just checking if you are still interested in pursuing this.

**Comment by 0x29a** [comment]
Hi @natabene, yes. PR that was blocking this work was merged yesterday, so I will be able to finish this current week.

cc @alangsto

**Comment by 0x29a** [comment]
@alangsto, I rebased branch. This is ready for review.

**Review by alangsto — APPROVED** [review]

**Comment by edx-webhook** [comment]
@0x29a 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/cc2olx&entry.867055334=https://github.com/edx/cc2olx/pull/32&entry.1484655318=https://github.com/0x29a&entry.752974735=2020-12-10+11:57&entry.1917517419=2021-01-15+14:41&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
