### PR TITLE
[BD-27] [TNL-7456] Find OLX alternative and add support for Essay problem type

### PR DESCRIPTION
**Pull request by shimulch**
This PR adds support for converting the Common Cartridge Essay problem to OLX Open Assessment.

**JIRA tickets**: 
- https://tasks.opencraft.com/browse/BB-2949

~~**Discussions**:~~

**Dependencies**: None

~~**Screenshots**:~~

~~**Sandbox URL**:~~

**Merge deadline**: None

**Testing instructions**:

1. Convert a Common Cartridge file with Essay ``cc.essay.v0p1`` type problem
2. Import into an edX instance with **ORA** installed. 
3. Essay type problems should be shown as ORA problems.

**Author notes and concerns**:
1. There is no equivalent for ORA ``criterion`` in Common Cartridge. So default ``criterions`` are added.
2. There is no equivalent for Sample Solution of Common Cartridge in ORA. Thus a HTML block has been created from the sample solution and added before the problem.

**Reviewers**
- [ ] @kaizoku
- [ ] @0x29a 
- [ ] edX reviewer[s] TBD

~~**Settings**~~

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @shimulch! I've created [BLENDED-588](https://openedx.atlassian.net/browse/BLENDED-588) to keep track of it in Jira.   More details are on the [BD-27](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1544912903/BD-27+Common+Cartridge+Converter) project page.

When this pull request is ready, tag your edX technical lead.

**Review by 0x29a — APPROVED** [review]
:+1:

Looks good.

- [x] I tested that:
- Tests are passing locally for both python versions.
- Essay problems are being rendered correctly:
    Screenshot from 2020-09-16 18-50-40
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~
- [x] Includes documentation
- [ ] ~~I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.~~

**Comment by shimulch** [comment]
Hi @azarembok, this PR is ready to review.

**Review by azarembok — APPROVED** [review]
Looks good, thanks!  Can you squash commits and then I'll merge it.

**Comment by shimulch** [comment]
@azarembok I've rebased with the master, fixed all conflicts, and quashed all commits to one.

**Pull request merged**
