### PR TITLE
BOM-2910: Replace Travis with GitHub CI

### PR DESCRIPTION
**Pull request by UsamaSadiq**
**Issue:** [BOM-2910](https://openedx.atlassian.net/browse/BOM-2910)

### Description
- Replace `Travis` with `GitHub CI`.

### CODE REVIEW

**Comment by UsamaSadiq** [comment]
Hi @schenedx, we are facing two test failures on GitHub CI. Would you be able to help us out on fixing these test failures as I couldn't figure out the reason why these are failing only on GitHub CI but passing on Travis.

**Comment by schenedx** [comment]
@alangsto Could you help the get the tests pass on this PR? If the tests are too difficult to maintain, do you know if we should consider skip them?

**Review by schenedx — COMMENTED** [review]
Why aren't we deleting the travis files in this PR? Will that come in a separate PR?

**Comment by UsamaSadiq** [comment]
I wanted the GitHub CI tests to pass first before removing Travis. I kept that for now to compare the test outputs on both platforms.

**Comment by UsamaSadiq** [comment]
Thanks @alangsto for help in fixing the tests. I'll squash the commits for the lint check to pass and then merge the PR.

**Review by alangsto — APPROVED** [review]
I know I made one of the changes - but the travis -> github action migration looks good

**Pull request merged**
