### PR TITLE
Black formatting

### PR DESCRIPTION
**Pull request by 0x29a**
This PR reformats all python code (with exception for OLX constructing code) using `black` tool, and enables formatting checking in Travis.

**Testing instructions**:

1. Add many blank lines somewhere in `setup.py`.
2. Run `tox`. It should fail.

**Reviewers**
- [ ] @alangsto

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @0x29a! I've created [OSPR-5269](https://openedx.atlassian.net/browse/OSPR-5269) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by alangsto** [comment]
I think this is a good idea. I will approve once you squash the commits

**Comment by 0x29a** [comment]
@alangsto, thanks! I squashed commits with a meaningful commit message and added PR description.

**Review by alangsto — APPROVED** [review]
LGTM

**Comment by edx-webhook** [comment]
@0x29a 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/cc2olx&entry.867055334=https://github.com/edx/cc2olx/pull/30&entry.1484655318=https://github.com/0x29a&entry.752974735=2020-12-01+15:52&entry.1917517419=2020-12-02+13:25&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by natabene** [comment]
@0x29a Thank you for your contribution!

**Pull request merged**
